#!/bin/bash

load inquirer

check() {
  if [ ! -f $SERVICE_CONFIG ]; then
     touch $SERVICE_CONFIG
  fi
  config::load_file $SERVICE_CONFIG

  if [ -z "$SERVICE_VSCODE_DOMAIN" ]; then
    inquirer::text "请输入 SERVICE_VSCODE_DOMAIN:" value
    config::set SERVICE_VSCODE_DOMAIN $value $SERVICE_CONFIG
  fi

  if [ -z "$SERVICE_VSCODE_DOREAMON_CLIENT_ID" ]; then
    inquirer::text "请输入 SERVICE_VSCODE_DOREAMON_CLIENT_ID:" value
    config::set SERVICE_VSCODE_DOREAMON_CLIENT_ID $value $SERVICE_CONFIG
  fi

  if [ -z "$SERVICE_VSCODE_DOREAMON_CLIENT_SECRET" ]; then
    inquirer::text "请输入 SERVICE_VSCODE_DOREAMON_CLIENT_SECRET:" value
    config::set SERVICE_VSCODE_DOREAMON_CLIENT_SECRET $value $SERVICE_CONFIG
  fi

  if [ -z "$SERVICE_VSCODE_ALLOW_USERNAMES" ]; then
    inquirer::text "请输入 SERVICE_VSCODE_ALLOW_USERNAMES:" value
    config::set SERVICE_VSCODE_ALLOW_USERNAMES $value $SERVICE_CONFIG
  fi

  # Fix code server permission on ~/.config => host: ${SERVICE_DATA}/vscode/config
  if [ ! -d "${SERVICE_DATA}/vscode" ]; then
    mkdir ${SERVICE_DATA}/vscode
  fi
  if [ "$(stat -c "%a" ${SERVICE_DATA}/vscode)" != "1777" ]; then
    sudo chmod 1777 ${SERVICE_DATA}/vscode
  fi
  
  # load again
  config::load_file $SERVICE_CONFIG
  
  # @TODO
  export SERVICE_VSCODE_DOMAIN=$SERVICE_VSCODE_DOMAIN
  export SERVICE_VSCODE_DOREAMON_CLIENT_ID=$SERVICE_VSCODE_DOREAMON_CLIENT_ID
  export SERVICE_VSCODE_DOREAMON_CLIENT_SECRET=$SERVICE_VSCODE_DOREAMON_CLIENT_SECRET
  export SERVICE_VSCODE_ALLOW_USERNAMES=$SERVICE_VSCODE_ALLOW_USERNAMES
}

check $@
